"""initial schema

Revision ID: 3ff41e26643b
Revises: 
Create Date: 2026-07-03 00:39:28.592300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff41e26643b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('jd_hash', sa.String(length=64), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_jd_hash'), 'job_descriptions', ['jd_hash'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resume_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('jd_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('match', sa.String(length=20), nullable=False),
    sa.Column('score', sa.String(length=10), nullable=False),
    sa.Column('full_analysis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_descriptions_jd_hash'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
